### ISSUE TITLE
readme update

### ISSUE THREAD

**Issue by LayneHu** [apache/openwhisk-runtime-dotnet#21] opened 2019-11-08 02:17 UTC
zip -r -0 helloDotNet.bin *  should be zip -r -0 helloDotNet.zip *

**Comment by shawnallen85** [comment] 2019-11-08 02:54
Duplicate of https://github.com/apache/openwhisk-runtime-dotnet/issues/10

**Comment by shawnallen85** [comment] 2019-11-22 16:53
This should now be resolved.

**Closed as completed** 2019-11-22 16:56 UTC
